AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Friendlines Serverless Backend

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Deployment environment (dev or prod)
  
  JwtSecretArn:
    Type: String
    Default: ''
    Description: ARN of the JWT secret in AWS Secrets Manager (required for prod)
  
  S3BucketName:
    Type: String
    Default: friendlines-media-local
    Description: S3 bucket name for media storage

Conditions:
  IsProduction: !Equals [!Ref Environment, 'prod']
  HasJwtSecretArn: !Not [!Equals [!Ref JwtSecretArn, '']]

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs20.x
    Architectures:
      - x86_64
    Environment:
      Variables:
        USERS_TABLE: !Ref UsersTable
        NEWSFLASHES_TABLE: !Ref NewsflashesTable
        GROUPS_TABLE: !Ref GroupsTable
        FRIENDSHIPS_TABLE: !Ref FriendshipsTable
        BOOKMARKS_TABLE: !Ref BookmarksTable
        DEVICE_TOKENS_TABLE: !Ref DeviceTokensTable
        MEDIA_BUCKET: !Ref MediaBucket
        ENVIRONMENT: !Ref Environment
        IS_LOCAL: !If [IsProduction, 'false', 'true']
        JWT_SECRET: !If [HasJwtSecretArn, !Sub '{{resolve:secretsmanager:${JwtSecretArn}:SecretString}}', 'local-dev-secret-change-in-production']

Resources:
  # API Gateway
  FriendlinesApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
        AllowOrigin: "'*'"

  # DynamoDB Tables
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: friendlines-users
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  NewsflashesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: friendlines-newsflashes
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: userId-timestamp-index
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST

  GroupsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: friendlines-groups
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  FriendshipsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: friendlines-friendships
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: friendId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: friendId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  BookmarksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: friendlines-bookmarks
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: newsflashId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: newsflashId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  DeviceTokensTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: friendlines-device-tokens
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: deviceId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: deviceId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  # S3 Bucket
  MediaBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
            AllowedOrigins:
              - '*'

  # S3 Bucket Policy for public read access
  MediaBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MediaBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub '${MediaBucket.Arn}/*'

  # Lambda Functions
  AuthFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: "es2022"
        EntryPoints:
          - src/handlers/auth.ts
    Properties:
      CodeUri: ./
      Handler: src/handlers/auth.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
      Events:
        Register:
          Type: Api
          Properties:
            RestApiId: !Ref FriendlinesApi
            Path: /auth/register
            Method: POST
        Login:
          Type: Api
          Properties:
            RestApiId: !Ref FriendlinesApi
            Path: /auth/login
            Method: POST
        GetMe:
          Type: Api
          Properties:
            RestApiId: !Ref FriendlinesApi
            Path: /auth/me
            Method: GET

  UsersFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: "es2022"
        EntryPoints:
          - src/handlers/users.ts
    Properties:
      CodeUri: ./
      Handler: src/handlers/users.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
      Events:
        GetUsers:
          Type: Api
          Properties:
            RestApiId: !Ref FriendlinesApi
            Path: /users
            Method: GET
        CreateUser:
          Type: Api
          Properties:
            RestApiId: !Ref FriendlinesApi
            Path: /users
            Method: POST
        GetUser:
          Type: Api
          Properties:
            RestApiId: !Ref FriendlinesApi
            Path: /users/{id}
            Method: GET

  NewsflashesFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: "es2022"
        EntryPoints:
          - src/handlers/newsflashes.ts
    Properties:
      CodeUri: ./
      Handler: src/handlers/newsflashes.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref NewsflashesTable
        - DynamoDBCrudPolicy:
            TableName: !Ref FriendshipsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
        - DynamoDBCrudPolicy:
            TableName: !Ref DeviceTokensTable
        - S3CrudPolicy:
            BucketName: !Ref MediaBucket
      Events:
        GetNewsflashes:
          Type: Api
          Properties:
            RestApiId: !Ref FriendlinesApi
            Path: /newsflashes
            Method: GET
        CreateNewsflash:
          Type: Api
          Properties:
            RestApiId: !Ref FriendlinesApi
            Path: /newsflashes
            Method: POST

  FriendshipsFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: "es2022"
        EntryPoints:
          - src/handlers/friendships.ts
    Properties:
      CodeUri: ./
      Handler: src/handlers/friendships.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FriendshipsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
        - DynamoDBCrudPolicy:
            TableName: !Ref DeviceTokensTable
      Events:
        GetReceivedRequests:
          Type: Api
          Properties:
            RestApiId: !Ref FriendlinesApi
            Path: /friend-requests/received
            Method: GET
        GetSentRequests:
          Type: Api
          Properties:
            RestApiId: !Ref FriendlinesApi
            Path: /friend-requests/sent
            Method: GET
        AcceptRequest:
          Type: Api
          Properties:
            RestApiId: !Ref FriendlinesApi
            Path: /friend-requests/{requestId}/accept
            Method: PUT
        RejectRequest:
          Type: Api
          Properties:
            RestApiId: !Ref FriendlinesApi
            Path: /friend-requests/{requestId}/reject
            Method: PUT
        GetFriendships:
          Type: Api
          Properties:
            RestApiId: !Ref FriendlinesApi
            Path: /friendships
            Method: GET
        GetFriends:
          Type: Api
          Properties:
            RestApiId: !Ref FriendlinesApi
            Path: /friends
            Method: GET
        SendRequest:
          Type: Api
          Properties:
            RestApiId: !Ref FriendlinesApi
            Path: /friendships
            Method: POST
        RemoveFriend:
          Type: Api
          Properties:
            RestApiId: !Ref FriendlinesApi
            Path: /friendships/{friendId}
            Method: DELETE

  GroupsFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: "es2022"
        EntryPoints:
          - src/handlers/groups.ts
    Properties:
      CodeUri: ./
      Handler: src/handlers/groups.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref GroupsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
      Events:
        GetGroups:
          Type: Api
          Properties:
            RestApiId: !Ref FriendlinesApi
            Path: /groups
            Method: GET
        CreateGroup:
          Type: Api
          Properties:
            RestApiId: !Ref FriendlinesApi
            Path: /groups
            Method: POST
        GetGroup:
          Type: Api
          Properties:
            RestApiId: !Ref FriendlinesApi
            Path: /groups/{id}
            Method: GET
        UpdateMembers:
          Type: Api
          Properties:
            RestApiId: !Ref FriendlinesApi
            Path: /groups/{id}/members
            Method: PUT
        DeleteGroup:
          Type: Api
          Properties:
            RestApiId: !Ref FriendlinesApi
            Path: /groups/{id}
            Method: DELETE

  FeedsFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: "es2022"
        EntryPoints:
          - src/handlers/feeds.ts
    Properties:
      CodeUri: ./
      Handler: src/handlers/feeds.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref NewsflashesTable
        - DynamoDBCrudPolicy:
            TableName: !Ref FriendshipsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref GroupsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
      Events:
        GetMainFeed:
          Type: Api
          Properties:
            RestApiId: !Ref FriendlinesApi
            Path: /feeds/main
            Method: GET
        GetGroupFeed:
          Type: Api
          Properties:
            RestApiId: !Ref FriendlinesApi
            Path: /feeds/group/{groupId}
            Method: GET

  UploadsFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: "es2022"
        EntryPoints:
          - src/handlers/uploads.ts
    Properties:
      CodeUri: ./
      Handler: src/handlers/uploads.handler
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref MediaBucket
      Events:
        GetPresignedUrl:
          Type: Api
          Properties:
            RestApiId: !Ref FriendlinesApi
            Path: /uploads/presigned-url
            Method: POST

  BookmarksFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: "es2022"
        EntryPoints:
          - src/handlers/bookmarks.ts
    Properties:
      CodeUri: ./
      Handler: src/handlers/bookmarks.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BookmarksTable
        - DynamoDBCrudPolicy:
            TableName: !Ref NewsflashesTable
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
      Events:
        GetBookmarks:
          Type: Api
          Properties:
            RestApiId: !Ref FriendlinesApi
            Path: /bookmarks
            Method: GET
        AddBookmark:
          Type: Api
          Properties:
            RestApiId: !Ref FriendlinesApi
            Path: /bookmarks
            Method: POST
        RemoveBookmark:
          Type: Api
          Properties:
            RestApiId: !Ref FriendlinesApi
            Path: /bookmarks/{newsflashId}
            Method: DELETE

  DevicesFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: "es2022"
        EntryPoints:
          - src/handlers/devices.ts
    Properties:
      CodeUri: ./
      Handler: src/handlers/devices.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DeviceTokensTable
      Events:
        RegisterToken:
          Type: Api
          Properties:
            RestApiId: !Ref FriendlinesApi
            Path: /devices/token
            Method: POST
        RemoveToken:
          Type: Api
          Properties:
            RestApiId: !Ref FriendlinesApi
            Path: /devices/token
            Method: DELETE

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${FriendlinesApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/"
  Environment:
    Description: "Deployment environment"
    Value: !Ref Environment
  UsersTableName:
    Description: "Users DynamoDB table name"
    Value: !Ref UsersTable
  NewsflashesTableName:
    Description: "Newsflashes DynamoDB table name"
    Value: !Ref NewsflashesTable
  MediaBucketName:
    Description: "S3 bucket name for media storage"
    Value: !Ref MediaBucket
