/**
 * i18next type definitions for type-safe translations.
 * Auto-generated by i18next-cli - run `npm run i18n:types` to update.
 */

import 'i18next';

// Import the resources type (will be generated by i18next-cli)
// For now, we define a basic CustomTypeOptions

declare module 'i18next' {
  interface CustomTypeOptions {
    defaultNS: 'common';
    resources: {
      common: Record<string, string>;
      auth: Record<string, unknown>;
      feed: Record<string, string>;
      newsflash: Record<string, string>;
      groups: Record<string, string>;
      profile: Record<string, string>;
      friends: Record<string, string>;
      saved: Record<string, string>;
      nav: Record<string, string>;
      a11y: Record<string, string>;
      errors: Record<string, string>;
      creation: Record<string, string>;
    };
  }
}
