/**
 * Auto-generated by i18next-cli types command.
 * Do not edit manually - run `npm run i18n:types` to regenerate.
 */

// This file will be populated by i18next-cli after running `npm run i18n:types`
// For now, define a basic structure that matches our namespaces

import common from '../i18n/locales/en/common.json';
import auth from '../i18n/locales/en/auth.json';
import feed from '../i18n/locales/en/feed.json';
import newsflash from '../i18n/locales/en/newsflash.json';
import groups from '../i18n/locales/en/groups.json';
import profile from '../i18n/locales/en/profile.json';
import friends from '../i18n/locales/en/friends.json';
import saved from '../i18n/locales/en/saved.json';
import nav from '../i18n/locales/en/nav.json';
import a11y from '../i18n/locales/en/a11y.json';
import errors from '../i18n/locales/en/errors.json';
import creation from '../i18n/locales/en/creation.json';

const resources = {
  common,
  auth,
  feed,
  newsflash,
  groups,
  profile,
  friends,
  saved,
  nav,
  a11y,
  errors,
  creation,
} as const;

export default resources;
